
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqevlvoleqfbubapnubp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZXZsdm9sZXFmYnViYXBudWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTQxNDUsImV4cCI6MjA2Mjk3MDE0NX0.Z0thcnNDae9ztuEfEiXVxebSL6fVT56OtE8ZXNQyZno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
